from app_props import *

from tweepy.streaming import StreamListener
from datetime import datetime
import redis


class TweetsOutputConsumer(StreamListener):
	"""
	Class to consume all tweets generated by twitter streamer to an output source
	"""

	def __init__(self, producer, redisclient):
		"""
		:param producer : Kafka producer client
		:param redisclient : Redis client
		"""
		self.producer = producer
		self.redisclient = redisclient

	def on_data(self, data):
		""" Method to send the streaming real time tweets to a kafka topic
		"""
		try:
			print("==============="+"sending new kafka record"+"=================")
			self.producer.send(KAFKA_TOPIC, data.encode('utf-8'))
			key = datetime.utcnow().strftime('%H')+':'+datetime.utcnow().strftime('%M')
			print(key)
			print(self.redisclient.ping())
			self.redisclient.incr(key,1)
			return True
		except BaseException as e:
		    print("Error on_data %s" % str(e))
		return True

	def on_error(self, status):
	    print(status)



